# Generated by Django 5.2.4 on 2025-07-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                ("icon", models.CharField(max_length=100, verbose_name="Ícone")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("execution_date", models.DateField(verbose_name="Data de execução")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pendente"),
                            ("C", "Concluída"),
                            ("A", "Em andamento"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "categorias",
                    models.ManyToManyField(
                        to="tasks.category", verbose_name="Categorias"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dono da tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["-execution_date"],
            },
        ),
    ]
